language: java
sudo: false # faster builds

jdk:
  - oraclejdk8

# script:
#   - mvn clean package -DskipTests=true  -f ./pom.xml


script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 5da3a823-3e30-4093-b028-cc65a392abce